options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'python:3.9-slim'
    entrypoint: 'sh'
    args: ['-c', 'pip install --upgrade pip && pip install -r requirements.txt']

  - name: 'python:3.9-slim'
    entrypoint: 'python'
    args: ['ClinicalTrials_gov_API.py']  # Jupyter Notebook ではなく、スクリプトとして実行

timeout: 600s
