steps:
  # 依存関係をインストールするステップ
  - name: 'python:3.9-slim'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🔍 Checking workspace contents..."
        ls -al
        echo "⚙️ Installing dependencies..."
        pip install --upgrade pip
        pip install --target=/workspace/packages -r requirements.txt
        echo "📦 Installed packages:"
        pip list
    env:
      - "PYTHONPATH=/workspace/packages"

  # スクリプトを実行するステップ
  - name: 'python:3.9-slim'
    entrypoint: 'python'
    args:
      - '-c'
      - |
        import sys
        sys.path.append('/workspace/packages')  # パスを追加
        import requests
        import pandas
        print("✅ Successfully imported requests and pandas!")
        exec(open("ClinicalTrials_gov_API.py").read())  # スクリプトを実行
    env:
      - "PYTHONPATH=/workspace/packages"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 600s
