steps:
  # 1️⃣ Docker イメージのビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/mimetic-obelisk-440100-n9/my-repo/clinical-api:latest"
      - "."

  # 2️⃣ Artifact Registry へプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/mimetic-obelisk-440100-n9/my-repo/clinical-api:latest"

  # 3️⃣ Cloud Run へデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy clinical-api \
          --image us-central1-docker.pkg.dev/mimetic-obelisk-440100-n9/my-repo/clinical-api:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

images:
  - "us-central1-docker.pkg.dev/mimetic-obelisk-440100-n9/my-repo/clinical-api:latest"

timeout: 900s
