options:
  logging: CLOUD_LOGGING_ONLY  # Cloud Logging のみに変更

steps:
  - name: 'python:3.9'
    entrypoint: 'sh'
    args: ['-c', 'pip install --upgrade pip && pip install nbconvert papermill']

  - name: 'python:3.9'
    entrypoint: 'jupyter'
    args: ['nbconvert', '--to', 'script', 'ClinicalTrials_gov_API.ipynb']

  - name: 'python:3.9'
    entrypoint: 'papermill'
    args: ['ClinicalTrials_gov_API.ipynb', 'output.ipynb']

timeout: 600s
