options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 依存関係をインストールするステップ
  - name: 'python:3.9-slim'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🔍 Checking workspace contents..."
        ls -al
        echo "⚙️ Installing dependencies..."
        pip install --upgrade pip
        pip install --target=/workspace/packages -r requirements.txt
        echo "📦 Installed packages:"
        pip list

  # スクリプトを実行するステップ
  - name: 'python:3.9-slim'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "🚀 Running script..."
        PYTHONPATH="/workspace/packages:$PYTHONPATH" python ClinicalTrials_gov_API.py

timeout: 600s
